package com.mbv.inventory.dao;

import java.util.List;

import com.mbv.inventory.bean.VpGdnBean;
import com.mbv.inventory.entity.VpGdnDtlEntity;

public interface VpGdnDtlEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_gdn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_gdn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int insert(VpGdnDtlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_gdn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int insertSelective(VpGdnDtlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_gdn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    VpGdnDtlEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_gdn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int updateByPrimaryKeySelective(VpGdnDtlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_gdn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int updateByPrimaryKey(VpGdnDtlEntity record);
    
    int insertVpGdnDtlBatch(List<VpGdnDtlEntity> list);

	List<VpGdnDtlEntity> selectVpGdnDtlByVpGdnId(Long id);

	int deleteByVpGdnId(Long id);
	
	public List<VpGdnDtlEntity> selectByVpGdnBeanAndProdNum(VpGdnBean bean);
}