package com.mbv.inventory.dao;

import java.util.List;

import com.mbv.inventory.entity.VpGrnDtlEntity;

public interface VpGrnDtlEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int insert(VpGrnDtlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int insertSelective(VpGrnDtlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    VpGrnDtlEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int updateByPrimaryKeySelective(VpGrnDtlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn_dtl
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int updateByPrimaryKey(VpGrnDtlEntity record);
    
    int insertVpGrnDtlBatch(List<VpGrnDtlEntity> list);

	List<VpGrnDtlEntity> selectVpGrnDtlByVpGrnId(Long id);

	int deleteByVpGrnId(Long id);
}