package com.mbv.inventory.dao;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.mbv.inventory.bean.VpGrnBean;
import com.mbv.inventory.entity.VpGrnEntity;

public interface VpGrnEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    int insert(VpGrnEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    int insertSelective(VpGrnEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    VpGrnEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    int updateByPrimaryKeySelective(VpGrnEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_grn
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    int updateByPrimaryKey(VpGrnEntity record);
    
    public List<VpGrnEntity> selectByParams(VpGrnBean bean, RowBounds rb);
    
    public int selectByParamsCount(VpGrnBean bean);
    
    public VpGrnEntity selectByVpGrnEntity(VpGrnEntity vpGrnEntity);
    
    public String getMaxDocCode(String seqName);

	VpGrnEntity selectByDocCode(String docCode);
}