package com.mbv.inventory.dao;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.mbv.inventory.bean.WarehProdTranBean;
import com.mbv.inventory.entity.VpWarehProdTranEntity;

public interface VpWarehProdTranEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_wareh_prod_tran
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_wareh_prod_tran
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int insert(VpWarehProdTranEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_wareh_prod_tran
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int insertSelective(VpWarehProdTranEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_wareh_prod_tran
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    VpWarehProdTranEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_wareh_prod_tran
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int updateByPrimaryKeySelective(VpWarehProdTranEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vp_wareh_prod_tran
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    int updateByPrimaryKey(VpWarehProdTranEntity record);
    
    /**
	 * @功能描述：根据条件查询出入库事务信息
	 * @2015年9月6日
	 * @param
	 * @version
	 */
	List<VpWarehProdTranEntity> selectWarehProdTranByParams(
			WarehProdTranBean bean, RowBounds rowBounds);

	/**
     * @功能描述：根据条件查询出入库记录数
     * @2015年9月6日
     * @param
     * @version
     */
	Integer selectWarehProdTranByParamsCount(WarehProdTranBean bean);

	/**
	 * 批量插入事务日志表
	 * @param prodTranList
	 * @return
	 */
	int insertVpWarehProdTranBatch(List<VpWarehProdTranEntity> prodTranList);
}