package com.mbv.inventory.entity;

import java.io.Serializable;

public class VpGdnDtlEntity implements Serializable{
	
	private static final long serialVersionUID = -3389204823577634337L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_gdn_dtl.id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_gdn_dtl.vp_gdn_id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private Long vpGdnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_gdn_dtl.prod_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private String prodNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_gdn_dtl.qty
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private int qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_gdn_dtl.remark
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_gdn_dtl.id
     *
     * @return the value of vp_gdn_dtl.id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_gdn_dtl.id
     *
     * @param id the value for vp_gdn_dtl.id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_gdn_dtl.vp_gdn_id
     *
     * @return the value of vp_gdn_dtl.vp_gdn_id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public Long getVpGdnId() {
        return vpGdnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_gdn_dtl.vp_gdn_id
     *
     * @param vpGdnId the value for vp_gdn_dtl.vp_gdn_id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setVpGdnId(Long vpGdnId) {
        this.vpGdnId = vpGdnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_gdn_dtl.prod_num
     *
     * @return the value of vp_gdn_dtl.prod_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public String getProdNum() {
        return prodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_gdn_dtl.prod_num
     *
     * @param prodNum the value for vp_gdn_dtl.prod_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setProdNum(String prodNum) {
        this.prodNum = prodNum == null ? null : prodNum.trim();
    }

    public int getQty() {
		return qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_gdn_dtl.remark
     *
     * @return the value of vp_gdn_dtl.remark
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_gdn_dtl.remark
     *
     * @param remark the value for vp_gdn_dtl.remark
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    
    @Override
    public boolean equals(Object obj) {
    	if(this == obj) return true;
    	if(obj instanceof VpGdnDtlEntity){
    		VpGdnDtlEntity vgde = (VpGdnDtlEntity) obj;
    		if(this.prodNum.equals(vgde.getProdNum())){
    			return true;
    		}
    	}
    	return false;
    }
    
    @Override
    public int hashCode() {
    	return 37 * 17 + this.prodNum.hashCode();
    }
}