package com.mbv.inventory.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.mbv.common.entity.BaseEntity;

public class VpGrnEntity extends BaseEntity implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6630326015395238938L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.id
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.doc_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String docCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.doc_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private Date docDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.unit_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String unitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.wareh_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String warehCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.ttl_qty
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private int ttlQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.rcpt_mode
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String rcptMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.rcpt_time
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private Date rcptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.rcpt_reason
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String rcptReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.doc_state
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String docState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.remark
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String remark;
    
    private int version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.create_user
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.create_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.last_modified_user
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private String lastModifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_grn.last_modified_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    private Date lastModifiedDate;
    
    private List<VpGrnDtlEntity> details;

	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public List<VpGrnDtlEntity> getDetails() {
		return details;
	}

	public void setDetails(List<VpGrnDtlEntity> details) {
		this.details = details;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.id
     *
     * @return the value of vp_grn.id
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.id
     *
     * @param id the value for vp_grn.id
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.doc_code
     *
     * @return the value of vp_grn.doc_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getDocCode() {
        return docCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.doc_code
     *
     * @param docCode the value for vp_grn.doc_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setDocCode(String docCode) {
        this.docCode = docCode == null ? null : docCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.doc_date
     *
     * @return the value of vp_grn.doc_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public Date getDocDate() {
        return docDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.doc_date
     *
     * @param docDate the value for vp_grn.doc_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setDocDate(Date docDate) {
        this.docDate = docDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.unit_code
     *
     * @return the value of vp_grn.unit_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.unit_code
     *
     * @param unitCode the value for vp_grn.unit_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.wareh_code
     *
     * @return the value of vp_grn.wareh_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getWarehCode() {
        return warehCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.wareh_code
     *
     * @param warehCode the value for vp_grn.wareh_code
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setWarehCode(String warehCode) {
        this.warehCode = warehCode == null ? null : warehCode.trim();
    }

    public int getTtlQty() {
		return ttlQty;
	}

	public void setTtlQty(int ttlQty) {
		this.ttlQty = ttlQty;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.rcpt_mode
     *
     * @return the value of vp_grn.rcpt_mode
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getRcptMode() {
        return rcptMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.rcpt_mode
     *
     * @param rcptMode the value for vp_grn.rcpt_mode
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setRcptMode(String rcptMode) {
        this.rcptMode = rcptMode == null ? null : rcptMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.rcpt_time
     *
     * @return the value of vp_grn.rcpt_time
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public Date getRcptTime() {
        return rcptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.rcpt_time
     *
     * @param rcptTime the value for vp_grn.rcpt_time
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setRcptTime(Date rcptTime) {
        this.rcptTime = rcptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.rcpt_reason
     *
     * @return the value of vp_grn.rcpt_reason
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getRcptReason() {
        return rcptReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.rcpt_reason
     *
     * @param rcptReason the value for vp_grn.rcpt_reason
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setRcptReason(String rcptReason) {
        this.rcptReason = rcptReason == null ? null : rcptReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.doc_state
     *
     * @return the value of vp_grn.doc_state
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getDocState() {
        return docState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.doc_state
     *
     * @param docState the value for vp_grn.doc_state
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setDocState(String docState) {
        this.docState = docState == null ? null : docState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.remark
     *
     * @return the value of vp_grn.remark
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.remark
     *
     * @param remark the value for vp_grn.remark
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.create_user
     *
     * @return the value of vp_grn.create_user
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.create_user
     *
     * @param createUser the value for vp_grn.create_user
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.create_date
     *
     * @return the value of vp_grn.create_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.create_date
     *
     * @param createDate the value for vp_grn.create_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.last_modified_user
     *
     * @return the value of vp_grn.last_modified_user
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public String getLastModifiedUser() {
        return lastModifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.last_modified_user
     *
     * @param lastModifiedUser the value for vp_grn.last_modified_user
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setLastModifiedUser(String lastModifiedUser) {
        this.lastModifiedUser = lastModifiedUser == null ? null : lastModifiedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_grn.last_modified_date
     *
     * @return the value of vp_grn.last_modified_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_grn.last_modified_date
     *
     * @param lastModifiedDate the value for vp_grn.last_modified_date
     *
     * @mbggenerated Wed Sep 09 12:01:02 CST 2015
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}