package com.mbv.inventory.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class VpWarehProdTranEntity implements Serializable {
    
	private static final long serialVersionUID = 8261276444207854514L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.wareh_code
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private String warehCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.prod_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private String prodNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.tran_date
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private Date tranDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.tran_time
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private Date tranTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.doc_type
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private String docType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.doc_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private String docNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.tran_qty
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private BigDecimal tranQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.stk_on_hand
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private BigDecimal stkOnHand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.qty_committed
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private BigDecimal qtyCommitted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.qty_on_lock
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private BigDecimal qtyOnLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.last_modified_user
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private String lastModifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vp_wareh_prod_tran.last_modified_date
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    private Date lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.id
     *
     * @return the value of vp_wareh_prod_tran.id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.id
     *
     * @param id the value for vp_wareh_prod_tran.id
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.wareh_code
     *
     * @return the value of vp_wareh_prod_tran.wareh_code
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public String getWarehCode() {
        return warehCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.wareh_code
     *
     * @param warehCode the value for vp_wareh_prod_tran.wareh_code
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setWarehCode(String warehCode) {
        this.warehCode = warehCode == null ? null : warehCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.prod_num
     *
     * @return the value of vp_wareh_prod_tran.prod_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public String getProdNum() {
        return prodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.prod_num
     *
     * @param prodNum the value for vp_wareh_prod_tran.prod_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setProdNum(String prodNum) {
        this.prodNum = prodNum == null ? null : prodNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.tran_date
     *
     * @return the value of vp_wareh_prod_tran.tran_date
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public Date getTranDate() {
        return tranDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.tran_date
     *
     * @param tranDate the value for vp_wareh_prod_tran.tran_date
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setTranDate(Date tranDate) {
        this.tranDate = tranDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.tran_time
     *
     * @return the value of vp_wareh_prod_tran.tran_time
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public Date getTranTime() {
        return tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.tran_time
     *
     * @param tranTime the value for vp_wareh_prod_tran.tran_time
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setTranTime(Date tranTime) {
        this.tranTime = tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.doc_type
     *
     * @return the value of vp_wareh_prod_tran.doc_type
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public String getDocType() {
        return docType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.doc_type
     *
     * @param docType the value for vp_wareh_prod_tran.doc_type
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setDocType(String docType) {
        this.docType = docType == null ? null : docType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.doc_num
     *
     * @return the value of vp_wareh_prod_tran.doc_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public String getDocNum() {
        return docNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.doc_num
     *
     * @param docNum the value for vp_wareh_prod_tran.doc_num
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setDocNum(String docNum) {
        this.docNum = docNum == null ? null : docNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.tran_qty
     *
     * @return the value of vp_wareh_prod_tran.tran_qty
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public BigDecimal getTranQty() {
        return tranQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.tran_qty
     *
     * @param tranQty the value for vp_wareh_prod_tran.tran_qty
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setTranQty(BigDecimal tranQty) {
        this.tranQty = tranQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.stk_on_hand
     *
     * @return the value of vp_wareh_prod_tran.stk_on_hand
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public BigDecimal getStkOnHand() {
        return stkOnHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.stk_on_hand
     *
     * @param stkOnHand the value for vp_wareh_prod_tran.stk_on_hand
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setStkOnHand(BigDecimal stkOnHand) {
        this.stkOnHand = stkOnHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.qty_committed
     *
     * @return the value of vp_wareh_prod_tran.qty_committed
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public BigDecimal getQtyCommitted() {
        return qtyCommitted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.qty_committed
     *
     * @param qtyCommitted the value for vp_wareh_prod_tran.qty_committed
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setQtyCommitted(BigDecimal qtyCommitted) {
        this.qtyCommitted = qtyCommitted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.qty_on_lock
     *
     * @return the value of vp_wareh_prod_tran.qty_on_lock
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public BigDecimal getQtyOnLock() {
        return qtyOnLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.qty_on_lock
     *
     * @param qtyOnLock the value for vp_wareh_prod_tran.qty_on_lock
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setQtyOnLock(BigDecimal qtyOnLock) {
        this.qtyOnLock = qtyOnLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.last_modified_user
     *
     * @return the value of vp_wareh_prod_tran.last_modified_user
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public String getLastModifiedUser() {
        return lastModifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.last_modified_user
     *
     * @param lastModifiedUser the value for vp_wareh_prod_tran.last_modified_user
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setLastModifiedUser(String lastModifiedUser) {
        this.lastModifiedUser = lastModifiedUser == null ? null : lastModifiedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vp_wareh_prod_tran.last_modified_date
     *
     * @return the value of vp_wareh_prod_tran.last_modified_date
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vp_wareh_prod_tran.last_modified_date
     *
     * @param lastModifiedDate the value for vp_wareh_prod_tran.last_modified_date
     *
     * @mbggenerated Thu Sep 10 11:02:49 CST 2015
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}