package com.mbv.biz.config.entity;

import java.io.Serializable;
import java.util.Date;

public class SysParameterEntity implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.id
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.parm_code
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private String parmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.para_val
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private String paraVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.description
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.status
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.create_user
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.create_date
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.last_update_user
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private String lastUpdateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_parameter.last_update_date
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.id
     *
     * @return the value of sys_parameter.id
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.id
     *
     * @param id the value for sys_parameter.id
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.parm_code
     *
     * @return the value of sys_parameter.parm_code
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public String getParmCode() {
        return parmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.parm_code
     *
     * @param parmCode the value for sys_parameter.parm_code
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setParmCode(String parmCode) {
        this.parmCode = parmCode == null ? null : parmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.para_val
     *
     * @return the value of sys_parameter.para_val
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public String getParaVal() {
        return paraVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.para_val
     *
     * @param paraVal the value for sys_parameter.para_val
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setParaVal(String paraVal) {
        this.paraVal = paraVal == null ? null : paraVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.description
     *
     * @return the value of sys_parameter.description
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.description
     *
     * @param description the value for sys_parameter.description
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.status
     *
     * @return the value of sys_parameter.status
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.status
     *
     * @param status the value for sys_parameter.status
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.create_user
     *
     * @return the value of sys_parameter.create_user
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.create_user
     *
     * @param createUser the value for sys_parameter.create_user
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.create_date
     *
     * @return the value of sys_parameter.create_date
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.create_date
     *
     * @param createDate the value for sys_parameter.create_date
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.last_update_user
     *
     * @return the value of sys_parameter.last_update_user
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.last_update_user
     *
     * @param lastUpdateUser the value for sys_parameter.last_update_user
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_parameter.last_update_date
     *
     * @return the value of sys_parameter.last_update_date
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_parameter.last_update_date
     *
     * @param lastUpdateDate the value for sys_parameter.last_update_date
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}