package com.mbv.biz.config.entity.sys;

import com.mbv.common.entity.BaseEntity;

public class ApplyModelEntity extends BaseEntity {
    /**
	 * TODO
	 */ 
	private static final long serialVersionUID = 5393981169063537900L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_model.id
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_model.CODE
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_model.model_name
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_model.column_name
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_model.col_des
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String colDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_model.bak
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String bak;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_model.id
     *
     * @return the value of apply_model.id
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_model.id
     *
     * @param id the value for apply_model.id
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_model.CODE
     *
     * @return the value of apply_model.CODE
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_model.CODE
     *
     * @param code the value for apply_model.CODE
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_model.model_name
     *
     * @return the value of apply_model.model_name
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_model.model_name
     *
     * @param modelName the value for apply_model.model_name
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_model.column_name
     *
     * @return the value of apply_model.column_name
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_model.column_name
     *
     * @param columnName the value for apply_model.column_name
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_model.col_des
     *
     * @return the value of apply_model.col_des
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getColDes() {
        return colDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_model.col_des
     *
     * @param colDes the value for apply_model.col_des
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setColDes(String colDes) {
        this.colDes = colDes == null ? null : colDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_model.bak
     *
     * @return the value of apply_model.bak
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getBak() {
        return bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_model.bak
     *
     * @param bak the value for apply_model.bak
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setBak(String bak) {
        this.bak = bak == null ? null : bak.trim();
    }
}