package com.mbv.biz.config.entity.sys;

import com.mbv.common.entity.BaseEntity;

public class DataDirectoryDetailEntity extends BaseEntity {
    /**
	 * TODO
	 */ 
	private static final long serialVersionUID = 1774640307457481374L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_directory_detail.id
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_directory_detail.CODE
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_directory_detail.code_detail
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String codeDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_directory_detail.name_detail
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String nameDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_directory_detail.description
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_directory_detail.number
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_directory_detail.id
     *
     * @return the value of data_directory_detail.id
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_directory_detail.id
     *
     * @param id the value for data_directory_detail.id
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_directory_detail.CODE
     *
     * @return the value of data_directory_detail.CODE
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_directory_detail.CODE
     *
     * @param code the value for data_directory_detail.CODE
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_directory_detail.code_detail
     *
     * @return the value of data_directory_detail.code_detail
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getCodeDetail() {
        return codeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_directory_detail.code_detail
     *
     * @param codeDetail the value for data_directory_detail.code_detail
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setCodeDetail(String codeDetail) {
        this.codeDetail = codeDetail == null ? null : codeDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_directory_detail.name_detail
     *
     * @return the value of data_directory_detail.name_detail
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getNameDetail() {
        return nameDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_directory_detail.name_detail
     *
     * @param nameDetail the value for data_directory_detail.name_detail
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setNameDetail(String nameDetail) {
        this.nameDetail = nameDetail == null ? null : nameDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_directory_detail.description
     *
     * @return the value of data_directory_detail.description
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_directory_detail.description
     *
     * @param description the value for data_directory_detail.description
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_directory_detail.number
     *
     * @return the value of data_directory_detail.number
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_directory_detail.number
     *
     * @param number the value for data_directory_detail.number
     *
     * @mbggenerated Mon Aug 24 09:51:46 CST 2015
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}