package com.mbv.biz.config.entity.sys;

import com.mbv.common.entity.BaseEntity;

import java.util.Date;
import java.util.List;

public class SysParamEntity extends BaseEntity {
	/**
	 * TODO
	 */
	private static final long serialVersionUID = 5964477801186016697L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.id
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.param_type
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private String paramType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.param_desc
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private String paramDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.param_value
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private String paramValue;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.is_valid
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private String isValid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.create_oper
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private String createOper;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.create_time
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.modify_oper
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private String modifyOper;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.modify_time
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private Date modifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.note
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private String note;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_param.is_globle
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	private String isGloble;

	/**
	 * 系统参数明细的集合
	 */
	private List<SysParamDetailEntity> details;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.id
	 * 
	 * @return the value of sys_param.id
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.id
	 * 
	 * @param id
	 *            the value for sys_param.id
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.param_type
	 * 
	 * @return the value of sys_param.param_type
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public String getParamType() {
		return paramType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.param_type
	 * 
	 * @param paramType
	 *            the value for sys_param.param_type
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setParamType(String paramType) {
		this.paramType = paramType == null || "".equals(paramType) ? null
				: paramType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.param_desc
	 * 
	 * @return the value of sys_param.param_desc
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public String getParamDesc() {
		return paramDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.param_desc
	 * 
	 * @param paramDesc
	 *            the value for sys_param.param_desc
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setParamDesc(String paramDesc) {
		this.paramDesc = paramDesc == null ? null : paramDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.param_value
	 * 
	 * @return the value of sys_param.param_value
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public String getParamValue() {
		return paramValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.param_value
	 * 
	 * @param paramValue
	 *            the value for sys_param.param_value
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setParamValue(String paramValue) {
		this.paramValue = paramValue == null || "".equals(paramValue) ? null
				: paramValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.is_valid
	 * 
	 * @return the value of sys_param.is_valid
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public String getIsValid() {
		return isValid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.is_valid
	 * 
	 * @param isValid
	 *            the value for sys_param.is_valid
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setIsValid(String isValid) {
		this.isValid = isValid == null ? null : isValid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.create_oper
	 * 
	 * @return the value of sys_param.create_oper
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public String getCreateOper() {
		return createOper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.create_oper
	 * 
	 * @param createOper
	 *            the value for sys_param.create_oper
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setCreateOper(String createOper) {
		this.createOper = createOper == null ? null : createOper.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.create_time
	 * 
	 * @return the value of sys_param.create_time
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.create_time
	 * 
	 * @param createTime
	 *            the value for sys_param.create_time
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.modify_oper
	 * 
	 * @return the value of sys_param.modify_oper
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public String getModifyOper() {
		return modifyOper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.modify_oper
	 * 
	 * @param modifyOper
	 *            the value for sys_param.modify_oper
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setModifyOper(String modifyOper) {
		this.modifyOper = modifyOper == null ? null : modifyOper.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.modify_time
	 * 
	 * @return the value of sys_param.modify_time
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.modify_time
	 * 
	 * @param modifyTime
	 *            the value for sys_param.modify_time
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.note
	 * 
	 * @return the value of sys_param.note
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.note
	 * 
	 * @param note
	 *            the value for sys_param.note
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_param.is_globle
	 * 
	 * @return the value of sys_param.is_globle
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public String getIsGloble() {
		return isGloble;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_param.is_globle
	 * 
	 * @param isGloble
	 *            the value for sys_param.is_globle
	 * 
	 * @mbggenerated Thu Aug 20 09:44:05 CST 2015
	 */
	public void setIsGloble(String isGloble) {
		this.isGloble = isGloble == null ? null : isGloble.trim();
	}

	public List<SysParamDetailEntity> getDetails() {
		return details;
	}

	public void setDetails(List<SysParamDetailEntity> details) {
		this.details = details;
	}

}