package com.mbv.biz.config.entity.sys;

import com.mbv.common.entity.BaseEntity;

public class SysParamDetailEntity extends BaseEntity {
    /**
	 * TODO
	 */ 
	private static final long serialVersionUID = 8578117379006820452L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_detail.id
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_detail.sysParamDetail
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    private String sysparamdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_detail.value
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_detail.description
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_detail.is_valiate
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    private String isValiate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_detail.param_type
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    private String paramType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_detail.id
     *
     * @return the value of sys_param_detail.id
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_detail.id
     *
     * @param id the value for sys_param_detail.id
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_detail.sysParamDetail
     *
     * @return the value of sys_param_detail.sysParamDetail
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public String getSysparamdetail() {
        return sysparamdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_detail.sysParamDetail
     *
     * @param sysparamdetail the value for sys_param_detail.sysParamDetail
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public void setSysparamdetail(String sysparamdetail) {
        this.sysparamdetail = sysparamdetail == null ? null : sysparamdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_detail.value
     *
     * @return the value of sys_param_detail.value
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_detail.value
     *
     * @param value the value for sys_param_detail.value
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_detail.description
     *
     * @return the value of sys_param_detail.description
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_detail.description
     *
     * @param description the value for sys_param_detail.description
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_detail.is_valiate
     *
     * @return the value of sys_param_detail.is_valiate
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public String getIsValiate() {
        return isValiate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_detail.is_valiate
     *
     * @param isValiate the value for sys_param_detail.is_valiate
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public void setIsValiate(String isValiate) {
        this.isValiate = isValiate == null ? null : isValiate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_detail.param_type
     *
     * @return the value of sys_param_detail.param_type
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_detail.param_type
     *
     * @param paramType the value for sys_param_detail.param_type
     *
     * @mbggenerated Thu Aug 20 09:44:05 CST 2015
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }
}