package com.mbv.biz.config.service;

import java.util.List;

import com.mbv.biz.config.entity.SysParameterEntity;
import com.mbv.common.exception.MbvException;

public interface SysParameterService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    int deleteByPrimaryKey(Integer id) throws MbvException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    int insert(SysParameterEntity record) throws MbvException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    int insertSelective(SysParameterEntity record) throws MbvException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    SysParameterEntity selectByPrimaryKey(Integer id) throws MbvException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    int updateByPrimaryKeySelective(SysParameterEntity record) throws MbvException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_parameter
     *
     * @mbggenerated Thu Sep 24 16:37:48 CST 2015
     */
    int updateByPrimaryKey(SysParameterEntity record) throws MbvException;
    
    /**
	 * @功能描述： 根据条件查询字典信息
	 * @2015年9月9日
	 * @param
	 * @version
	 */
	public List<SysParameterEntity> queryByParams(SysParameterEntity entity,int offset,int limit) throws MbvException;
	
	public SysParameterEntity selectByPramCode(String paramCode) throws MbvException;
}
